source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LVGSwiftSystemSoundServices_Example', :exclusive => true do
  pod 'LVGSwiftSystemSoundServices', :path => '../'
end

target 'LVGSwiftSystemSoundServices_Tests', :exclusive => true do
  pod 'LVGSwiftSystemSoundServices', :path => '../'

  
end
