# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
osx_image: xcode7.3
script:
- open -b com.apple.iphonesimulator
- set -o pipefail && xcodebuild test -workspace Example/LVGSwiftSystemSoundServices.xcworkspace -scheme LVGSwiftSystemSoundServices-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
