source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

install! 'cocoapods',
    :deterministic_uuids => false

target 'Tests-iOS' do
    platform :ios, '8.0'
    pod 'LVGSwiftSystemSoundServices', :path => '../'
end

target 'Tests-OSX' do
    platform :osx, '10.10'
    pod 'LVGSwiftSystemSoundServices', :path => '../'
end