source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'Tests-iOS' do
    platform :ios, '8.0'
    pod 'LVGSwiftSystemSoundServices', :path => '../'
end

target 'Tests-macOS' do
    platform :osx, '10.10'
    pod 'LVGSwiftSystemSoundServices', :path => '../'
end
